export const fhu_const = {
  TYPE_OF_BIN: 'Type Of Bin',
  BIN_QTY: 'Bin Qty',
  BIN_SERVICE_TYPE: 'Bin Service Type',
  BIN_RATE: 'Bin Rate',
  BIN_TOTAL_AMT: 'Bin Total Amount',
  BIN_INSTALLED_QTY :'Bin installed Quantity'
};

export const vm_const = {
  TYPE_OF_VM: 'Type Of VM',
  VM_QTY: 'VM Qty',
  VM_DEPLOYMENT_TYPE: 'VM Deployment Type',
  VM_RENTAL_AMT: 'VM Rental Amount',
  VM_BUYOUT_AMT: 'VM Buyout Amount',
  VM_TOTAL_AMT: 'VM Total Amount',
  VM_SERVICE_FREQUENCY: 'VM Service Frequency',
  VM_INSTALLED_QTY:'VM installed Quantity'
};

export const sim_const = {
  SIM_QTY: 'Sim Quantity',
  SIM_PRICE: 'Sim Price',
  SIM_BRAND: 'Sim Brand',
  SIM_NUMBER: 'Sim Number',
  SIM_INSTALLED_QTY :'Sim installed Quantity'
};

export const vm_pads = {
  VM_PAD_BRAND: 'VM Pad Brand',
  VM_PAD_QTY: 'VM Pad Quantity',
  VM_PAD_COST: 'VM Pad Cost',
  VM_PAD_TOTAL_COST: 'VM Pad Total Cost',
  VM_PADS_INSTALLED_QTY:'VM Pad Installed Quantity'
};

export const sanitary_pad = {
  SANITARY_PAD_BRAND: 'Sanitary Pad Brand',
  SANITARY_PAD_QTY: 'Sanitary Pad Quantity',
  SANITARY_PAD_COST: 'Sanitary Pad Cost',
  SANITARY_PAD_TOTAL_COST: 'Sanitary Pad Total Cost',
};

export const misc_const = {
  SO_NO: 'So Number',
  PO_NO: 'Po Number',
  PAYMENT_TERMS: 'Payment Terms',
  BILLING_FAQ: 'BillingFaq',
  BILLING_ADD:'Billing Address',
  SITE_ADDRESS:'siteAddress',
  SO_RECEIVED_DATE: 'So Received Date',
  CONTRACT_START_DATE: 'Contract Start Date',
  CONTRACT_END_DATE: 'Contract End Date',
  FEMALE_COUNT: 'Female Count',
  SALES_LEAD: 'Sales Lead',
  SPOC_NAME: 'SPOC Name',
  SPOC_EMAIL: 'SPOC Email',
  SPOC_PHONE: 'SPOC Phone No',
};

export const client_const = {
  BRANCH_NAME: 'Branch Name',
  CLIENT_NAME: 'Client Name',
  CLIENT_TYPE: 'Client Type',
  CLIENT_USER_TYPE: 'Client User Type',
  FEMALE_HYGENE_UNIT: 'femaleHygieneUnit',
  VENDING_MACHINE: 'vendingMachine',
  SIM_RECHARGE: 'sim',
  SANITARY_PADS: 'sanitaryPads',
  VM_PADS: 'vendingMachinePads',
  SPOC: 'spoc',
  CLIENT_CITY: 'City',
  INDUSTRY_TYPE : 'Industry Type',
  GST_NUMBER : 'gstNumber',
  PINCODE :'pincode',
  REQUEST_TYPE : 'Request Type'
};

export const dbError_const = {
  SALES_LEAD:'Sales Lead',
  FEMALE_COUNT:'Female Count',
  CONTRACT_START_DATE: 'contractStartDate',
  CONTRACT_END_DATE:'contractEndDate',
  SO_RECIEVED_DATE:'soReceivedDate',
  SO_NUMBER : 'soNumber',
  BILLING_FAQ:'billingFaq',
  PAYMENT_TERMS:'paymentTerms',
  SITE_ADDRESS:'siteAddress',
  BILLING_ADDRESS:'billingAddress',
  BRANCH_NAME:'branchName',
  CLIENT_ID: 'clientId',
  USER_TYPE:'userType',
  PO_NUMBER:'poNumber',
  CITY_ID:'cityId',
  ERRORS:'ERRORS',
  ERROR_MSG:'Error Message',
  ERROR_PATH:'Error Path'
}

export const product_const = {
  CLIENT_ON_BOARDING_PRODUCT:'Client onboarding Product',
  STICKERS : 'stickers',
  AGENT_NAME : 'Agent Name',
  INVOICE_AMOUNT :'Invoice Amount',
  TOTAL_INSTALLATION_COST : 'Total installation cost',
  INSTALLATION_STATUS :'Installation status',
  INSTALLATION_COMPLETION_DATE : 'Installation Completed At',
  INSTALLATION_DATE : 'Installation Date',
  INSTALLATION_MONTH :"Installation month"
}

  export const CLIENT_INFO = {
    STATE : "State",
    CITY : "City",
    CLIENT_TYPE : "Client Type",
    REQUEST_TYPE : "Request Type",
    CLIENT_NAME : "Client Name",
    BRANCH_NAME : "Branch Name",
    BILLING_ADDRESS : "Billing Address",
    SITE_ADDRESS : "siteAddress",
    PINCODE : "pincode",
    GST_NO : "gstNumber",
    INDUSTRY_TYPE : "Industry Type",
    FEMALE_COUNT : "femaleCount",
    IFM_CLIENT_NAME : "IFM Client Name",
    USERNAME : "Username",
    EMAIL : "Email",
    PASSWORD : "Password",
    CONTRACT_START_DATE: "Contract Start Date",
    CONTRACT_END_DATE: "Contract End Date",
    SALES_LEAD: "Sales Lead",
  }

  export const PRODUCT_INFO = {
    CITY: "City",
    CLIENT_NAME: "Client Name",
    BRANCH_NAME: "Branch Name",
    SO_NUMBER: "So Number",
    SO_RECEIVED_DATE: "So Received Date",
    PO_NUMBER: "Po Number",
    PO_TYPE: "Po Type",
    PAYMENT_TERMS: "Payment Terms",
    BILLING_FAQ: "BillingFaq",
    CONTRACT_START_DATE: "Contract Start Date",
    CONTRACT_END_DATE: "Contract End Date",
    TYPE_OF_BIN: "Type Of Bin",
    BIN_SERVICE_TYPE: "Bin Service Type",
    BIN_QTY: "Bin Qty",
    BIN_INSTALLED_QUANTITY: "Bin installed Quantity",
    BIN_RATE: "Bin Rate",
    BIN_TOTAL_AMOUNT: "Bin Total Amount",
    TYPE_OF_VM: "Type Of VM",
    VM_DEPLOYMENT_TYPE: "VM Deployment Type",
    VM_SERVICE_FREQUENCY: "VM Service Frequency",
    VM_QTY: "VM Qty",
    VM_INSTALLED_QUANTITY: "VM installed Quantity",
    VM_BUYOUT_AMOUNT: "VM Buyout Amount",
    VM_RENTAL_AMOUNT: "VM Rental Amount",
    VM_TOTAL_AMOUNT: "Vm Total Amount",
    SIM_NUMBER: "Sim Number",
    SIM_BRAND: "Sim Brand",
    SIM_QUANTITY: "Sim Quantity",
    SIM_INSTALLED_QUANTITY: "Sim installed Quantity",
    SIM_PRICE: "Sim Price",
    VM_PAD_BRAND: "VM Pad Brand",
    VM_PAD_QUANTITY: "VM Pad Quantity",
    VM_PAD_INSTALLED_QUANTITY: "VM Pad Installed Quantity",
    VM_PAD_COST: "VM Pad Cost",
    VM_PAD_TOTAL_COST: "VM Pad Total Cost",
    SANITARY_PAD_BRAND: "Sanitary Pad Brand",
    SANITARY_PAD_QUANTITY: "Sanitary Pad Quantity",
    SANITARY_PAD_COST: "Sanitary Pad Cost",
    SANITARY_PAD_TOTAL_COST: "Sanitary Pad Total Cost",
    SPOC_NAME: "SPOC Name",
    SPOC_PHONE_NO: "SPOC Phone No",
    SPOC_EMAIL: "SPOC Email",
    SALES_LEAD: "Sales Lead",
    CLIENT_ON_BOARDING_PRODUCT: "Client onboarding Product",
    STICKERS: "stickers",
    AGENT_NAME: "Agent Name",
    INVOICE_AMOUNT: "Invoice Amount",
    TOTAL_INSTALLATION_COST: "Total installation cost",
    INSTALLATION_DATE: "Installation Date",
    INSTALLATION_MONTH: "Installation month",
    INSTALLATION_STATUS: "Installation status",
    INSTALLATION_COMPLETED_AT: "Installation Completed At"
  };

  export const SERVICES = {
    CITY:"City",
    CLIENT_NAME:"Client Name",
    BRANCH_NAME:"Branch Name",
    SO_NUMBER:"So Number",
    SERVICE_DATE:"Service Date",
    SERVICE_MONTH:"Service Month",
    TYPE_OF_BIN:"Type Of Bin",
    BIN_SERVICE_TYPE:"Bin Service Type",
    BIN_TOTAL_QTY: "Bin Total Qty",
    BIN_SERVICED_QTY:"Bin Serviced Qty",
    BIN_SERVICE_COST:'Bin Service Cost',
    BIN_INVOICE_AMOUNT : "Bin Invoice Amount",
    BIN_INVOICE_SUBMITTED : "Is Bin Invoice Submitted to client",
    BIN_INVOICE_NO: "Bin Invoice Number",
    BIN_MAINTENANCE_PARTS : "Bin Maintenance Parts",
    BIN_MAINTENANCE_PARTS_QTY:"Bin Maintenance Parts Quantity",
    WASTED_PAD_COLLECTION_QTY: "Waste Pad Collection Quantity in grams",
    TYPE_OF_VM:"Type Of VM",
    VM_DEPLOYMENT_TYPE:"VM Deployment Type",
    VM_SERVICE_FREQUENCY:"VM Service Frequency",
    VM_SERVICED_QTY:"VM Serviced Qty",
    VM_BUYOUT_AMOUNT:"VM Buyout Amount",
    VM_RENTAL_AMOUNT:"VM Rental Amount",
    VM_TOTAL_AMOUNT:"VM Total Amount",
    VM_SERVICE_COST:"VM Service Cost",
    VM_MAINTENANCE_PARTS:"VM Maintenance Parts",
    VM_MAINTENANCE_PARTS_QTY:"VM Maintenance Parts Quantity",
    VM_INVOICE_AMOUNT:"VM Invoice Amount",
    VM_INVOICE_NO:"VM invoice number",
    RS5_PAD_REFILLING_QTY:"₹5 Pad Refilling Quantity",
    RS10_PAD_REFILLING_QTY:"₹10 Pad Refilling Quantity",
    RS5_COIN_COLLECTION_QTY:"₹5 Coin Collection Quantity",
    RS10_COIN_COLLECTION_QTY:"₹10 Coin Collection Quantity",
    RS5_PAD_SOLD_QTY:"₹5 Pad Sold Quantity",
    RS10_PAD_SOLD_QTY :"₹10 Pad Sold Quantity",
    PAD_SOLD_INVOICE_AMOUNT : "Pad Sold Invoice Amount",
    VEHICLE_USED_FOR_SERVICE:"vehicle used for service",
    SERVICE_RATING:"Service Rating",
    TOTAL_SERVICE_COST:"Total Service Cost",
    COMPLETED_ON : 'Service Completed On'
  }
  
